print ("Lee-Ann Jenica R. Monterey")
print ("Masaguisi, Santa Cruz Marinduque")
print ("November 5, 2002")
print ("Marinduque State College")
print ("BS Information Technology")
print ("2nd Year - Section: D")